version: '3'

tasks:
  default: 
    cmds: 
      - task -l

  clean:
    desc: Remove builded binaries
    cmds: 
      - rm -rf dist

  test:
    desc: Build all cmd
    cmds:
      - go test ./... -coverprofile=coverage.out *.go ; go tool cover -func=coverage.out ; go tool cover -html=coverage.out

  build:
    desc: Build all cmd
    cmds:
      - |
        command -v pass > /dev/null && export GITHUB_TOKEN=$(pass show home/bruno/github.com/token/goreleaser)
        goreleaser build --snapshot --clean

  release:
    desc: Release new version
    cmds:
      - |
        command -v pass > /dev/null && export GITHUB_TOKEN=$(pass show home/bruno/github.com/token/goreleaser)
        goreleaser release --clean --snapshot

  run:
    desc: run
    cmds: 
      - go run cmd/teacolors/teacolors.go