name: push

on: push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Get Go modules
        run: go mod tidy

      - name: Test
        run: go test -v ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.1.7
        with:
          report: 'true'
          chart: 'true'
          amend: 'true'